apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod
#  annotations:
#     cert-manager.io/issuer: letsencrypt-nginx
spec:
#  tls:
#    - hosts:
#     - cohort.rekeyole.site
#     secretName: letsencrypt-nginx
  rules:
    - host: cohort.rekeyole.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amazon-service
                port:
                  number: 3000
  ingressClassName: nginx
